services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "5174:5174"

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/gsm:/gsm